variable "project_name" { 
    description = "The name of the project, to be used in naming resources"
}

variable "project_id" { 
    description = "The name of the project in OpenStack"
}

variable volume_id {
    description = "the ID of the reserved storage volumne"
}

variable "floating_ip" { 
    description = "The floating IP reserved for the service"
}

variable "ssh_mosh_secgroup_id" { 
    description = "The ID of the security group for SSH/MOSH access"
}

variable "postgres_secgroup_id" { 
    description = "The ID of the security group for postgres access"
}

variable "vm_flavour" {
    description = "The VM flavour to create"
    default = "io.160GB"
}

variable "postgres_root_user" { 
    description = "postgres root user name"
}

variable "postgres_root_password" { 
    description = "postgres root user password (autogenerated if not given)"
    default = "" 
}

variable "postgres_database" { 
    description = "postgres default database name"
}

